server:
  port: 80
  basePath: ''
application:
  domain: juice-sh.op
  name: 'Cyber Arena'
  logo: logo2.png
  favicon: favicon.ico
  theme: blue-lightblue # Options: bluegrey-lightgreen blue-lightblue deeppurple-amber indigo-pink pink-bluegrey purple-green deeporange-indigo
  showVersionNumber: true
  showGitHubLinks: true
  numberOfRandomFakeUsers: 1
  altcoinName: Juicycoin
  privacyContactEmail: donotreply@owasp-juice.shop
  customMetricsPrefix: juiceshop
  social:
    twitterUrl: 'https://twitter.com/owasp_juiceshop'
    facebookUrl: 'https://www.facebook.com/owasp.juiceshop'
    slackUrl: 'http://owaspslack.com'
    redditUrl: 'https://www.reddit.com/r/owasp_juiceshop'
    pressKitUrl: 'https://github.com/OWASP/owasp-swag/tree/master/projects/juice-shop'
    questionnaireUrl: 'https://forms.gle/2Tr5m1pqnnesApxN8'
  recyclePage:
    topProductImage: fruit_press.jpg
    bottomProductImage: apple_pressings.jpg
  welcomeBanner:
    showOnFirstStart: true
    title: 'Bem-vindo a Cyber Arena!'
    message: "<p><strong>CECyber Arena</strong> é uma plataforma que reproduz uma aplicação Web real e que apresenta um grande número de falhas de segurança em sua estrutura. Os alunos são expostos a uma série de desafios, do nível básico ao avançado, que envolvem as 10 principais vulnerabilidades do projeto OWASP Top 10. Eles devem percorrer os exercícios de forma a identificar e corrigir as falhas encontradas.
              O treinamento no <strong>CECyber Arena</strong> permite que os profissionais desenvolvam o pensamento crítico e as habilidades técnicas necessárias para construir softwares muito mais seguros desde sua concepção, minimizando os riscos de ameaças cibernéticas e prejuízos à empresa.
              O CECyber Arena foi adaptado a partir da plataforma open source Juice Shop do OWASP (<i>Open Web Application Security Project</i>), organização sem fins lucrativos mantida por voluntários, que atua para melhorar a segurança dos softwares.</p>
              <h1><a href='https://cecyber.com/' target='_blank'>CECyber Centro de Excelência em Segurança Cibernética</a></h1>"
  cookieConsent:
    backgroundColor: '#546e7a'
    textColor: '#ffffff'
    buttonColor: '#558b2f'
    buttonTextColor: '#ffffff'
    message: 'Este site usa cookies para garantier a melhor experiência de rastreamento.'
    dismissText: 'Eu quero isso!'
    linkText: 'Mas espere!'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:donotreply@owasp-juice.shop'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
  promotion:
    video: JuiceShopJingle.mp4
    subtitles: JuiceShopJingle.vtt
  easterEggPlanet:
    name: Orangeuze
    overlayMap: orangemap2k.jpg
  googleOauth:
    clientId: '1005568560502-6hm16lef8oh46hr2d98vf2ohlnj4nfhq.apps.googleusercontent.com'
    authorizedRedirects:
      - { uri: 'https://demo.owasp-juice.shop' }
      - { uri: 'http://demo.owasp-juice.shop' }
      - { uri: 'https://juice-shop.herokuapp.com' }
      - { uri: 'http://juice-shop.herokuapp.com' }
      - { uri: 'https://preview.owasp-juice.shop' }
      - { uri: 'http://preview.owasp-juice.shop' }
      - { uri: 'https://juice-shop-staging.herokuapp.com' }
      - { uri: 'http://juice-shop-staging.herokuapp.com' }
      - { uri: 'http://juice-shop.wtf' }
      - { uri: 'http://localhost:3000', proxy: 'http://local3000.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:3000', proxy: 'http://local3000.owasp-juice.shop' }
      - { uri: 'http://localhost:4200', proxy: 'http://local4200.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:4200', proxy: 'http://local4200.owasp-juice.shop' }
      - { uri: 'http://192.168.99.100:3000', proxy: 'http://localmac.owasp-juice.shop' }
      - { uri: 'http://penguin.termina.linux.test:3000', proxy: 'http://localchromeos.owasp-juice.shop' }
challenges:
  showSolvedNotifications: true
  showHints: true
  restrictToTutorialsFirst: false
  overwriteUrlForProductTamperingChallenge: 'https://owasp.slack.com'
  xssBonusPayload: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/771984076&color=%23ff5500&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  safetyOverride: false
hackingInstructor:
  isEnabled: true
  avatarImage: JuicyBot_MedicalMask.png
products:
  -
    name: 'CompTIA CASP+'
    price: 1999.99
    deluxePrice: 0.99
    limitPerUser: 5
    description: 'Curso presencial.'
    image: Base_CompTIA_CASP.png
    reviews:
      - { text: 'Um dos meus favoritos!', author: admin }
  -
    name: 'CompTIA CySA+'
    description: 'Curso presencial.'
    price: 1999.99
    deluxePrice: 2.49
    image: Base_CompTIA_Cysa.png
    reviews:
      - { text: 'y0ur f1r3wall needs m0r3 musc13', author: uvogin }
  -
    name: 'CompTIA PenTest+'
    description: 'Curso presencial.'
    quantity: 0
    price: 1999.99
    image: Base_CompTIA_PenTest.png
    reviews:
      - { text: 'I bought it, would buy again. 5/7', author: admin }
  -
    name: 'CompTIA Security+'
    description: 'Curso presencial.'
    price: 1999.99
    image: Base_CompTIA_Security.png
  -
    name: 'CyberRange Defense Forensisc'
    description: 'Curso ao vivo'
    quantity: 1
    price: 5999.99
    deluxePrice: 1.99
    limitPerUser: 5
    image: Base_CyberRange_Defense_Forensisc.png
  -
    name: 'CyberRange Defence Incidente Responder'
    description: 'Curso ao vivo'
    quantity: 3
    price: 5999.99
    image: Base_CyberRange_Defence_Incidente_Responder.png
    reviews:
      - { text: 'Fry liked it too.', author: bender }
  -
    name: 'CyberRange Defense Analyst'
    description: 'Curso ao vivo'
    price: 5999.49
    limitPerUser: 5
    image: Base_CyberRange_Defense_Analyst.png
  -
    name: 'CyberRange Exploitation Analyst'
    description: 'Curso ao vivo'
    price: 5999.49
    image: Base_CyberRange_Exploitation_Analyst.png
  -
    name: 'CyberRange Infrastructure Support Specialist'
    description: 'Curso ao vivo'
    price: 5999.99
    image: Base_CyberRange_Infrastructure_Support_Specialist.png
    urlForProductTamperingChallenge: 'https://www.owasp.org/index.php/O-Saft'
  -
    name: 'CyberRange Operator'
    description: 'Curso ao vivo'
    price: 5999.99
    image: Base_CyberRange_Operator.png
    useForChristmasSpecialChallenge: true
  -
    name: 'CyberRange OT Operator'
    description: 'Curso ao vivo'
    price: 5999.99
    image: Base_CyberRange_OT_Operator.png
    keywordsForPastebinDataLeakChallenge:
      - hueteroneel
      - eurogium edule
  -
    name: 'CyberRange Vulnerability Assessment Analyst'
    description: 'Curso ao vivo'
    price: 5999.99
    image: Base_CyberRange_Vulnerability_Assessment_Analyst.png
    deletedDate: '2017-04-28'
  -
    name: 'DevSecOps 4Managers'
    description: 'Curso EAD'
    price: 999.00
    image: Base_DevSecOps_4Managers.png
  -
    name: 'DevSecOps 4TechLeaders'
    description: 'Curso EAD'
    price: 999.00
    image: Base_DevSecOps_4TechLeaders.png
  -
    name: 'DevSecOps 4Developers'
    description: 'Curso EAD'
    price: 999.00
    image: Base_DevSecOps_4Developers.png
  -
    name: 'OWASP TOP 10 - ARENA'
    description: 'Curso EAD'
    quantity: 0
    price: 999.00
    image: Base_OWASP_TOP_10_ARENA.png
  -
    name: 'CECyber Defense Analyst Formation'
    description: 'Curso presencial'
    price: 2999.99
    image: Base_CECyber_Defense_Analyst_Formation.png
    reviews:
      - { text: 'I straight-up gots nuff props fo''these tattoos!', author: rapper }
  -
    name: 'SOC Analyst Onboarding Formation'
    description: 'Curso presencial'
    price: 2999.99
    image: Base_SOC_Analyst_Onboarding_Formation.png
  -
    name: 'Incident Response Professional'
    description: 'Curso presencial'
    price: 2999.99
    image: Base_Incident_Response_Professional.png
  -
    name: 'Incident Response Specialist'
    description: 'Curso presencial'
    price: 2999.99
    quantity: 5
    limitPerUser: 5
    image: Base_Incident_Response_Specialist.png
    reviews:
      - { text: 'This thang would look phat on Bobby''s jacked fur coat!', author: rapper }
      - { text: 'Looks so much better on my uniform than the boring Starfleet symbol.', author: jim }
  -
    name: 'Forensics Analyst Formation'
    description: 'Curso presencial'
    price: 2999.99
    image: Base_Forensics_Analyst_Formation.png
  -
    name: 'Cybersecurity Specialist L1'
    description: 'Curso presencial'
    price: 2999.99
    image: Base_Cybersecurity_Specialist_L1.png
    reviews:
      - { text: 'Fresh out of a replicator.', author: jim }
  -
    name: 'Cybersecurity Specialist L2'
    description: 'Curso presencial'
    price: 2999.99
    image: Base_Cybersecurity_Specialist_L2.png
  -
    name: 'Cybersecurity Specialist L3'
    description: 'Curso presencial'
    price: 2999.99
    limitPerUser: 5
    image: Base_Cybersecurity_Specialist_L3.png
  -
    name: 'C-Level workshop'
    description: 'Curso ao vivo'
    price: 1999.99
    image: Base_CLevel_workshop.png
  -
    name: 'CISO and SOC Manager Program'
    description: 'Curso ao vivo'
    price: 1999.99
    image: Base_CISO_and_SOC_Manager_Program.png    # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
  -
    name: 'Data Privacy Officer Formation'
    description: 'Curso ao vivo'
    price: 1999.99
    quantity: 1
    image: Base_Data_Privacy_Officer_Formation.png
    reviews:
      - { text: "Mau Mau with bling-bling? Humans are so pathetic!", author: bender }
  -
    name: 'Data Privacy Workshop'
    description: 'Curso ao vivo'
    price: 1999.99
    image: Base_Data_Privacy_workshop.png
    deletedDate: '2017-07-01'
    reviews:
      - { text: "Ooooh, puny human playing Mau Mau, now?", author: bender }
  -
    name: 'Segurança em Home Office'
    description: 'Curso EAD'
    price: 199.00
    image: Base_Segurança_em_Home_Office.png
    reviews:
      - { text: "K33p5 y0ur ju1cy 5plu773r 70 y0ur53lf!", author: uvogin }
      - { text: "Puny mask for puny human weaklings!", author: bender }
  -
    name: 'Programa de Conscientização'
    description: 'Curso EAD'
    price: 199.00
    image: Base_Programa_de_Conscientização).png
    reviews:
      - { text: '0 st4rs f0r 7h3 h0rr1bl3 s3cur17y', author: uvogin }
  -
    name: 'Ethical Hacking Formation'
    description: 'Curso EAD'
    price: 499.00
    image: Base_Ethical_Hacking_Formation.png
    deletedDate: '2017-09-20'
    reviews:
      - { text: "Rad, dude!", author: rapper }
      - { text: "Looks spacy on Bones' new tricorder!", author: jim }
      - { text: "Will put one on the Planet Express ship's bumper!", author: bender }
  -
    name: 'Workshop de Segurança na Rede'
    description: 'Curso EAD'
    price: 199.00
    image: Base_Workshop_de_Segurança_na_Rede.png
    reviews:
      - { text: 'Even more interesting than watching Interdimensional Cable!', author: morty }
  -
    name: 'Segurança das Crianças na Rede'
    description: 'Curso EAD'
    price: 199.00
    quantity: 3
    limitPerUser: 1
    image: Base_Segurança_das_Crianças_na_Rede).png
    reviews:
      - { text: "Here yo' learn how tha fuck ta not show yo' goddamn phone on camera!", author: rapper }
  -
    name: 'IoT Security Analyst'
    description: 'Curso EAD'
    price: 499.00
    quantity: 0
    image: Base_IoT_Security_Analyst.png
    reviews:
      - { text: 'Wait for a 10$ Steam sale of Tabletop Simulator!', author: bjoernOwasp }
memories:
  -
    image: 'magn(et)ificent!-1571814229653.jpg'
    caption: 'Magn(et)ificent!'
    user: bjoernGoogle
  -
    image: 'my-rare-collectors-item!-[̲̅$̲̅(̲̅-͡°-͜ʖ-͡°̲̅)̲̅$̲̅]-1572603645543.jpg'
    caption: 'My rare collectors item! [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]'
    user: bjoernGoogle
ctf:
  showFlagsInNotifications: false
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
  countryMapping: ~
